/*
 * GoldstandardGUI.java
 * 
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, see <http://www.gnu.org/licenses/>.
 */

package de.uni_leipzig.informatik.pcai042.boa.gui.goldstandard;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
public class GoldstandardGUI extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button button_withdrawSentence;
	@AutoGenerated
	private Button button_addSentence;
	@AutoGenerated
	private Button button_add;
	@AutoGenerated
	private Button button_read;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private TextField textField_label;
	@AutoGenerated
	private TextField textField_sentence;
	@AutoGenerated
	private Label label_annotation;
	@AutoGenerated
	private Label label_sentence;
	@AutoGenerated
	private Button button_writeXML;
	@AutoGenerated
	private Button button_openXML;
	@AutoGenerated
	private Label label_home;
	@AutoGenerated
	private Embedded embedded_logo;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public GoldstandardGUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setCaption("close XML");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// embedded_logo
		embedded_logo = new Embedded();
		embedded_logo.setImmediate(false);
		embedded_logo.setWidth("-1px");
		embedded_logo.setHeight("-1px");
		embedded_logo.setSource(new ThemeResource(
				"img/component/embedded_icon.png"));
		embedded_logo.setType(1);
		embedded_logo.setMimeType("image/png");
		mainLayout.addComponent(embedded_logo, "top:10.0px;left:10.0px;");
		
		// label_home
		label_home = new Label();
		label_home.setImmediate(false);
		label_home.setWidth("-1px");
		label_home.setHeight("-1px");
		label_home.setValue("Home");
		mainLayout.addComponent(label_home, "top:60.0px;left:40.0px;");
		
		// button_openXML
		button_openXML = new Button();
		button_openXML.setCaption("open XML");
		button_openXML.setImmediate(true);
		button_openXML.setWidth("-1px");
		button_openXML.setHeight("-1px");
		mainLayout.addComponent(button_openXML, "top:160.0px;left:280.0px;");
		
		// button_writeXML
		button_writeXML = new Button();
		button_writeXML.setCaption("write XML");
		button_writeXML.setImmediate(true);
		button_writeXML.setWidth("-1px");
		button_writeXML.setHeight("-1px");
		mainLayout.addComponent(button_writeXML, "top:160.0px;left:458.0px;");
		
		// label_sentence
		label_sentence = new Label();
		label_sentence.setImmediate(false);
		label_sentence.setWidth("-1px");
		label_sentence.setHeight("-1px");
		label_sentence.setValue("Sentence:");
		mainLayout.addComponent(label_sentence, "top:220.0px;left:125.0px;");
		
		// label_annotation
		label_annotation = new Label();
		label_annotation.setImmediate(false);
		label_annotation.setWidth("-1px");
		label_annotation.setHeight("-1px");
		label_annotation.setValue("Annotation:");
		mainLayout.addComponent(label_annotation, "top:302.0px;left:125.0px;");
		
		// textField_sentence
		textField_sentence = new TextField();
		textField_sentence.setImmediate(false);
		textField_sentence.setWidth("340px");
		textField_sentence.setHeight("66px");
		textField_sentence.setSecret(false);
		mainLayout
				.addComponent(textField_sentence, "top:214.0px;left:240.0px;");
		
		// textField_label
		textField_label = new TextField();
		textField_label.setImmediate(false);
		textField_label.setWidth("160px");
		textField_label.setHeight("44px");
		textField_label.setSecret(false);
		mainLayout.addComponent(textField_label, "top:296.0px;left:240.0px;");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("162px");
		textField_1.setHeight("44px");
		textField_1.setSecret(false);
		mainLayout.addComponent(textField_1, "top:296.0px;left:418.0px;");
		
		// button_read
		button_read = new Button();
		button_read.setCaption("read");
		button_read.setImmediate(true);
		button_read.setWidth("-1px");
		button_read.setHeight("-1px");
		mainLayout.addComponent(button_read, "top:214.0px;left:630.0px;");
		
		// button_add
		button_add = new Button();
		button_add.setCaption("add");
		button_add.setImmediate(true);
		button_add.setWidth("-1px");
		button_add.setHeight("-1px");
		mainLayout.addComponent(button_add, "top:294.0px;left:630.0px;");
		
		// button_addSentence
		button_addSentence = new Button();
		button_addSentence.setCaption("add Sentence");
		button_addSentence.setImmediate(true);
		button_addSentence.setWidth("-1px");
		button_addSentence.setHeight("-1px");
		mainLayout
				.addComponent(button_addSentence, "top:414.0px;left:298.0px;");
		
		// button_withdrawSentence
		button_withdrawSentence = new Button();
		button_withdrawSentence.setCaption("withdraw Sentence");
		button_withdrawSentence.setImmediate(true);
		button_withdrawSentence.setWidth("-1px");
		button_withdrawSentence.setHeight("-1px");
		mainLayout.addComponent(button_withdrawSentence,
				"top:414.0px;left:409.0px;");
		
		return mainLayout;
	}

}